/**
 * The printable report: markdown in, one self-contained HTML page out.
 *
 * This is the thing chromium is pointed at. It is also, on a box with no
 * chromium, the thing that never gets made — see db/pdf-printer.js for what
 * happens instead.
 *
 * ⚠ SELF-CONTAINED IS A HARD REQUIREMENT, not a preference. The printer opens a
 * `file://` URL with no network and no profile: a stylesheet link, a webfont, a
 * CDN script would each fail silently and the PDF would come out looking like a
 * 1994 document with no styling at all — a failure that produces a FILE, so
 * nothing errors and nobody finds out until she opens it. So everything is
 * inline: the CSS is in a <style>, the charts are SVG markup generated by
 * db/charts.js, and there is not one external reference in the output.
 *
 * FONTS ARE NAMED, NOT INHERITED, for the same reason. `system-ui` under a
 * headless browser with no desktop resolves to whatever fontconfig feels like,
 * which on a server is frequently a CJK fallback with Latin glyphs. The stacks
 * below name what is actually installed (Liberation, DejaVu, Nimbus) before
 * falling back.
 *
 * PAGE GEOMETRY LIVES IN CSS. The printer drives chromium with --print-to-pdf,
 * which takes no page-size arguments, so `@page` here is the only thing that
 * sets the paper and the margins. That is not a workaround — it is where CSS
 * paged media puts them.
 *
 * WHAT IT CANNOT DO, said plainly so nobody goes looking for it twice: page
 * numbers, and any other running header or footer. Chrome does not implement the
 * `@page` margin boxes that would generate them, and `Page.printToPDF`'s
 * headerTemplate/footerTemplate are only reachable over the DevTools socket,
 * which this path deliberately does not open. The `position: fixed` trick that
 * the internet recommends for this DOES repeat on every page and does NOT stay
 * in the margin — it was tried, it printed over a table row on page two, and the
 * warning is in the CSS at the point where someone would add it back.
 * So: title and date on page one, in the header, and nowhere else.
 */

const md = require('./markdown');
const charts = require('./charts');

const { formatLocalTime } = require('./datetime');
/**
 * Print CSS.
 *
 * Sized for reading on paper rather than on screen: 10.5pt body, generous
 * leading, a measure that does not run the full width of the page. The colours
 * are the same ink and grid tokens the charts use, so a table and a figure on
 * the same page belong to one document.
 */
function styles(pageSize) {
  return `
@page {
  size: ${pageSize === 'A4' ? 'A4' : 'Letter'};
  margin: 20mm 18mm 22mm;
}

/* Backgrounds and fills are part of the content here — a table header band and
   a pie slice are not decoration — so they must survive the print path. */
* { -webkit-print-color-adjust: exact; print-color-adjust: exact; box-sizing: border-box; }

body {
  font-family: "Liberation Serif", "Nimbus Roman", "DejaVu Serif", Georgia, serif;
  font-size: 10.5pt;
  line-height: 1.5;
  color: #0b0b0b;
  margin: 0;
}

/* Headings in sans against a serif body: the contrast does the work that size
   alone would otherwise have to, so a heading can stay close to body size and
   the document does not shout. */
h1, h2, h3, h4, h5, h6,
.doc-header, .chart-figure, table, .md-code {
  font-family: "Liberation Sans", "DejaVu Sans", "Nimbus Sans", Arial, sans-serif;
}

h1 { font-size: 19pt; line-height: 1.2; margin: 0 0 4pt; letter-spacing: -0.01em; }
/* The document's title is in the header; an h1 inside the body is the writer's
   own top heading and must sit BELOW it in the hierarchy. At the same 19pt the
   two read as two titles — which is what happens whenever the opening heading is
   not word-for-word the job title, so the exact-match dedupe below does not fire. */
main h1 { font-size: 15pt; margin: 16pt 0 6pt; }
main h1:first-child { margin-top: 0; }
h2 { font-size: 13pt; margin: 18pt 0 5pt; padding-bottom: 3pt; border-bottom: 1px solid #e1e0d9; }
h3 { font-size: 11.5pt; margin: 14pt 0 4pt; }
h4, h5, h6 {
  font-size: 10pt; margin: 12pt 0 3pt;
  text-transform: uppercase; letter-spacing: 0.05em; color: #52514e;
}
/* A heading at the foot of a page with its section overleaf is the single most
   common way a generated PDF looks unedited. */
h1, h2, h3, h4, h5, h6 { break-after: avoid; page-break-after: avoid; }

p { margin: 0 0 8pt; orphans: 3; widows: 3; }
ul, ol { margin: 0 0 8pt; padding-left: 20pt; }
li { margin: 2pt 0; }
li > ul, li > ol { margin-bottom: 0; }
.md-task { list-style: none; margin-left: -14pt; }

blockquote {
  margin: 0 0 8pt; padding: 2pt 0 2pt 10pt;
  border-left: 2px solid #c3c2b7; color: #52514e;
}

a { color: #1c5cab; text-decoration: none; }
hr { border: none; border-top: 1px solid #e1e0d9; margin: 14pt 0; }

code {
  font-family: "Liberation Mono", "DejaVu Sans Mono", "Nimbus Mono PS", monospace;
  font-size: 9pt;
  background: #f4f4f1;
  padding: 0.5pt 3pt;
  border-radius: 2pt;
}
pre.md-code {
  font-size: 8.5pt;
  line-height: 1.4;
  background: #f7f7f4;
  border: 1px solid #e1e0d9;
  border-radius: 3pt;
  padding: 7pt 9pt;
  margin: 0 0 10pt;
  /* Wrapped, not scrolled: a printed page has no scrollbar, and a code block
     that overflows the margin is a code block with its right-hand side missing. */
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  break-inside: avoid-page;
}
pre.md-code code { background: none; padding: 0; font-size: inherit; }
pre.md-code[data-lang]::before {
  content: attr(data-lang);
  display: block; margin-bottom: 4pt;
  font-size: 7pt; text-transform: uppercase; letter-spacing: 0.08em; color: #898781;
}

table.md-table {
  border-collapse: collapse;
  width: 100%;
  font-size: 9pt;
  margin: 0 0 10pt;
  break-inside: auto;
}
.md-table-wrap { margin: 0 0 10pt; }
table.md-table th, table.md-table td {
  border-bottom: 1px solid #e1e0d9;
  padding: 4pt 6pt;
  text-align: left;
  vertical-align: top;
}
table.md-table th {
  background: #f4f4f1;
  font-size: 7.5pt;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #52514e;
  border-bottom: 1px solid #c3c2b7;
}
/* A row split across a page break is unreadable; the header repeating on the
   continuation is what makes a long table survive one. */
table.md-table tr { break-inside: avoid; page-break-inside: avoid; }
table.md-table thead { display: table-header-group; }

.chart-figure {
  margin: 10pt 0 14pt;
  break-inside: avoid-page;
  page-break-inside: avoid;
  text-align: center;
}
.chart-title {
  font-size: 9.5pt; font-weight: 700; text-align: left;
  margin-bottom: 5pt; color: #0b0b0b;
}
.chart-svg { max-width: 100%; height: auto; }
.chart-caption { font-size: 8.5pt; color: #52514e; text-align: left; margin: 4pt 0 0; }

img { max-width: 100%; height: auto; }

/* --- The document's own chrome ------------------------------------------- */

.doc-header { margin-bottom: 16pt; padding-bottom: 8pt; border-bottom: 2px solid #0b0b0b; }
.doc-meta { font-size: 8.5pt; color: #52514e; margin-top: 3pt; }
.doc-task {
  font-size: 9pt; color: #52514e; margin: 8pt 0 14pt;
  padding: 6pt 8pt; background: #f7f7f4; border-left: 2px solid #c3c2b7;
}

/* ⚠ THERE IS NO RUNNING FOOTER, AND THERE MUST NOT BE ONE HERE.
   The obvious trick — position: fixed, nudged into the bottom margin — is
   documented all over the web as "repeats on every printed page in Chromium".
   It does repeat. It does NOT land in the margin: on a real three-page print
   (Chromium 151) it painted at the same offset on pages 2 and 3, on top of a
   table row and then on top of a blockquote. Page one looked perfect, which is
   exactly why this is written down — the failure is invisible in every
   single-page test.
   A real running footer needs Page.printToPDF's footerTemplate, which needs the
   DevTools socket, which needs a WebSocket client this deliberately does not
   have. So the title and date sit in the header on page one and nowhere else,
   and anything added here must be checked on a document that runs past one
   page. */

.doc-note {
  margin-top: 18pt; padding-top: 6pt;
  border-top: 1px solid #e1e0d9;
  font-size: 8pt; color: #898781;
}
`;
}

/**
 * A ```chart fence, or null to let it stay a code block.
 *
 * The FALLBACK IS A TABLE, not a hole. A chart spec that cannot be drawn still
 * has numbers in it, and numbers in rows are worth more than an apology — the
 * only thing lost is the shape. Only when even the data cannot be read does this
 * hand back null and let the block print as the JSON it is, which at least shows
 * her what the run was trying to say.
 */
function chartFence(lang, code) {
  if (lang !== 'chart') return null;
  return charts.renderChart(code) || charts.chartFallbackTable(code);
}

/** A date a person would write, for the header and the running footer. */
function stamp(date) {
  return formatLocalTime(date, { style: 'full' });
}

/**
 * Build the printable page.
 *
 * @param {Object} opts
 * @param {string} opts.title      what the job called itself
 * @param {string} opts.body       the result, as markdown
 * @param {string} [opts.task]     the instruction the run followed
 * @param {Date}   [opts.date]     when it finished
 * @param {string} [opts.note]     a line at the end — usually why a run stopped short
 * @param {string} [opts.pageSize] Letter | A4
 * @returns {string} a complete HTML document
 */
function buildReportHtml({ title, body, task = '', date = new Date(), note = '', pageSize = 'Letter' } = {}) {
  const heading = String(title || 'Background job').trim();
  const when = stamp(date);
  const content = md.renderMarkdown(String(body || ''), { fence: chartFence });

  // The h1 is the report's own title, so a body that opens with the same title
  // as a markdown heading would print it twice. Dropped only when it is the very
  // first thing and it matches — never searched for further down, where a
  // repeated heading is a real section.
  const deduped = content.replace(
    new RegExp(`^<h1 class="md-h md-h1">${escapeRe(md.esc(heading))}</h1>\\s*`),
    ''
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${md.esc(heading)}</title>
<style>${styles(pageSize)}</style>
</head>
<body>
<header class="doc-header">
  <h1>${md.esc(heading)}</h1>
  <div class="doc-meta">Background job · ${md.esc(when)}</div>
</header>
${task ? `<div class="doc-task"><strong>The job:</strong> ${md.esc(task)}</div>` : ''}
<main>
${deduped}
</main>
${note ? `<div class="doc-note">${md.esc(note)}</div>` : ''}
</body>
</html>`;
}

/** Escape a string for use inside a RegExp. */
function escapeRe(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = { buildReportHtml, chartFence };
